version: "3"

services:
  mysql:
    container_name: mysql
    hostname: mysql
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: node_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - node-network

  node_app:
    container_name: node_app
    hostname: node_app
    depends_on:
      - mysql
    build: .
    ports:
      - "8000:8000"
    networks:
      - node-network
    volumes:
      - ./:/usr/app

  nginx:
    build: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "8080:80"
    depends_on:
      - node_app
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
